services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=database-1.cp2ek86cm4p0.us-east-1.rds.amazonaws.com
      - DB_NAME=togglemaster
      - DB_USER=testedb
      - DB_PORT=5432